name: CI .NET Core

on:
    push:
        branches:
          - develop  
          - release/*
          - feature/*
          - fix/*



jobs:
  build:
    env:
        BUILD_CONFIG: Release
        PROJECT_NAME: ClosedXML.TableReader


    name: Build Start
    runs-on: ubuntu-latest

    steps:
    - name: Set env. aux vars
      run: |
        echo "SOLUTION_NAME=${PROJECT_NAME}.sln">> $GITHUB_ENV
        echo "TEST_PROJECT_PATH=tests/${PROJECT_NAME}.Test/${PROJECT_NAME}.Test.csproj" >> $GITHUB_ENV
        echo "PROJECT_PATH=src/${PROJECT_NAME}/${PROJECT_NAME}.csproj" >> $GITHUB_ENV
 

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies                
      run: dotnet restore $SOLUTION_NAME
    - name: Test - [FuncionalTest]
      run: dotnet test $TEST_PROJECT_PATH --no-restore --verbosity normal
    - name: Build 
      run: dotnet build $PROJECT_PATH --configuration $BUILD_CONFIG --no-restore 
